# Generated by Django 6.0.1 on 2026-01-20 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('estado_entrega', models.CharField(max_length=20)),
                ('profesor_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.profesorcurso')),
            ],
        ),
    ]
