# Generated by Django 6.0.1 on 2026-05-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlCarga',
        ),
    ]
