# Generated by Django 6.0.1 on 2026-01-23 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('FALTA', 'Falta'), ('RETRASO', 'Retraso')], max_length=10),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='students.estudiante'),
        ),
        migrations.CreateModel(
            name='AsistenciaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('BLOQUEADA', 'Bloqueada')], default='ENVIADA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_asistencia', to='academics.curso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_asistencia_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Asistencia',
                'verbose_name_plural': 'Sesiones de Asistencia',
                'unique_together': {('curso', 'fecha')},
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='sesion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='attendance.asistenciasesion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('sesion', 'estudiante')},
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='registrado_por',
        ),
    ]
