# Generated by Django 6.0.1 on 2026-02-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_asistencia_options_alter_asistencia_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('FALTA', 'Falta'), ('RETRASO', 'Retraso'), ('LICENCIA', 'Licencia')], max_length=10),
        ),
    ]
