# Generated by Django 6.0.1 on 2026-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_asistencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('ATRASO', 'Atraso'), ('LICENCIA', 'Licencia')], max_length=10),
        ),
    ]
