# Generated by Django 6.0.1 on 2026-04-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_asistencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='uniforme',
            field=models.BooleanField(default=True),
        ),
    ]
