services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: seguimiento_staging_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.config.settings.production
    depends_on:
      - db
    volumes:
      - staticfiles_staging:/app/staticfiles
      - mediafiles_staging:/app/media
    # Ya NO exponemos el puerto al exterior
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8002:80"   # El mundo ve el puerto 8002, Nginx escucha en 80 internamente
    volumes:
      - ./nginx/nginx.staging.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles_staging:/app/staticfiles:ro
      - mediafiles_staging:/app/media:ro
    depends_on:
      - web
    restart: always

volumes:
  postgres_staging_data:
  staticfiles_staging:
  mediafiles_staging: