-- ============================================================
-- SEGUIMIENTO ACADÉMICO — Seed de producción
-- Materias (13) + Asignaciones Profesor-Curso-Materia (225)
-- Generado automáticamente desde la base de datos local
-- ============================================================
-- Compatible con PostgreSQL.
-- Para ejecutar:
--   docker compose -f docker-compose.staging.yml exec -T db psql -U <usuario> -d <base> < seed_produccion.sql
-- ============================================================

-- ── 1. MATERIAS ──────────────────────────────────────────────────

INSERT INTO academics_materia (nombre) VALUES ('Artes Plásticas y Visuales')         ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Ciencias Naturales: Biología')        ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Ciencias Sociales')                   ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Cosmovisiones Filosofía Psicología')  ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Educación Física y Deportes')         ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Educación Musical')                   ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Física')                              ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Lengua Castellana y Originaria')      ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Lengua Extranjera')                   ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Matemática')                          ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Química')                             ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Técnica Tecnológica General')         ON CONFLICT (nombre) DO NOTHING;
INSERT INTO academics_materia (nombre) VALUES ('Valores, Espiritualidades y Religiones') ON CONFLICT (nombre) DO NOTHING;

-- ── 2. ASIGNACIONES PROFESOR — CURSO — MATERIA ───────────────────
-- Usa subqueries para buscar IDs por username, grado+paralelo y nombre de materia.
-- ON CONFLICT DO NOTHING evita duplicados si se ejecuta más de una vez.

-- delmi-5-2026 | Lengua Castellana y Originaria
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delmi-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delmi-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delmi-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delmi-5-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delmi-5-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delmi-5-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- villma-6-2026 | Cosmovisiones Filosofía Psicología
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='villma-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- sandra-6-2026 | Ciencias Naturales: Biología / Química / Física
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='sandra-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- yola-5-2026 | Lengua Castellana y Originaria
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='yola-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='yola-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='yola-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='yola-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='yola-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='yola-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='yola-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- veronica-6-2026 | Ciencias Sociales
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='veronica-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='veronica-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='veronica-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='veronica-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='veronica-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- teddy-6-2026 | Ciencias Naturales: Biología / Física / Química
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='teddy-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- alejandra-8-2026 | Lengua Castellana y Originaria
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='alejandra-8-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='alejandra-8-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='alejandra-8-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='alejandra-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='alejandra-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='alejandra-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='alejandra-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Lengua Castellana y Originaria') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- roberto-8-2026 | Lengua Extranjera
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='roberto-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- constancia-9-2026 | Ciencias Sociales
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='constancia-9-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='constancia-9-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='constancia-9-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- magaly-7-2026 | Ciencias Naturales: Biología
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='magaly-7-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='magaly-7-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='magaly-7-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='magaly-7-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='magaly-7-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='magaly-7-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- jose-7-2026 | Cosmovisiones Filosofía Psicología
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jose-7-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jose-7-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jose-7-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jose-7-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jose-7-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jose-7-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jose-7-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jose-7-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jose-7-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Cosmovisiones Filosofía Psicología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- lourdes-5-2026 | Ciencias Sociales
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lourdes-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lourdes-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lourdes-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lourdes-5-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- raul-5-2026 | Matemática
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='raul-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='raul-5-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='raul-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='raul-5-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='raul-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- jaime-6-2026 | Ciencias Naturales: Biología
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jaime-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jaime-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jaime-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jaime-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jaime-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='jaime-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- delfin-7-2026 | Educación Musical
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='delfin-7-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- rosalia-5-2026 | Matemática
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rosalia-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rosalia-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- gisela-7-2026 | Química / Física
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='gisela-7-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='gisela-7-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='gisela-7-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='gisela-7-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Física') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='gisela-7-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='gisela-7-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='gisela-7-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='gisela-7-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='gisela-7-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Química') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- julia-6-2026 | Artes Plásticas y Visuales
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='julia-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- lidia-6-2026 | Técnica Tecnológica General
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lidia-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Técnica Tecnológica General') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lidia-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Técnica Tecnológica General') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lidia-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Técnica Tecnológica General') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lidia-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Técnica Tecnológica General') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lidia-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Técnica Tecnológica General') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='lidia-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Técnica Tecnológica General') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- guillermina-6-2026 | Ciencias Sociales
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='guillermina-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='guillermina-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='guillermina-6-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- ivan-6-2026 | Educación Musical
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='ivan-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='ivan-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='ivan-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='ivan-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='ivan-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='ivan-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='ivan-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='ivan-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='ivan-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Musical') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- rolando-4-2026 | Educación Física y Deportes
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='rolando-4-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- mario-4-2026 | Artes Plásticas y Visuales
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='mario-4-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='mario-4-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='mario-4-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='mario-4-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='mario-4-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='mario-4-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='mario-4-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='mario-4-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='mario-4-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Artes Plásticas y Visuales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- kathia-4-2026 | Ciencias Naturales: Biología
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='kathia-4-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='kathia-4-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='kathia-4-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='kathia-4-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='kathia-4-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='kathia-4-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Naturales: Biología') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- marlene-5-2026 | Educación Física y Deportes
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='marlene-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Educación Física y Deportes') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- elvira-6-2026 | Matemática
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='elvira-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='elvira-6-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='elvira-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='elvira-6-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- maxima-8-2026 | Matemática
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='maxima-8-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='maxima-8-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='maxima-8-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='maxima-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- juan-8-2026 | Ciencias Sociales
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='juan-8-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='juan-8-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='juan-8-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='juan-8-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='juan-8-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Ciencias Sociales') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- nilda-5-2026 | Valores, Espiritualidades y Religiones
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='nilda-5-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- maria-5-2026 | Valores, Espiritualidades y Religiones
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='maria-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='maria-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='maria-5-2026'), (SELECT id FROM academics_curso WHERE grado='3ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='maria-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='maria-5-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Valores, Espiritualidades y Religiones') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- felipe-8-2026 | Matemática
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='felipe-8-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='felipe-8-2026'), (SELECT id FROM academics_curso WHERE grado='5to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='felipe-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='felipe-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='felipe-8-2026'), (SELECT id FROM academics_curso WHERE grado='6to' AND paralelo='D'), (SELECT id FROM academics_materia WHERE nombre='Matemática') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- victoria-6-2026 | Lengua Extranjera
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='victoria-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='victoria-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='victoria-6-2026'), (SELECT id FROM academics_curso WHERE grado='1ro' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='victoria-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='victoria-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='victoria-6-2026'), (SELECT id FROM academics_curso WHERE grado='2do' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='victoria-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='A'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='victoria-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='B'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;
INSERT INTO academics_profesorcurso (profesor_id, curso_id, materia_id) SELECT (SELECT id FROM users_user WHERE username='victoria-6-2026'), (SELECT id FROM academics_curso WHERE grado='4to' AND paralelo='C'), (SELECT id FROM academics_materia WHERE nombre='Lengua Extranjera') ON CONFLICT (profesor_id, curso_id, materia_id) DO NOTHING;

-- ============================================================
-- FIN — 13 materias + 234 asignaciones
-- ============================================================
