# Generated by Django 6.0.1 on 2026-03-06 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_fcmdevice_unique_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmdevice',
            options={'verbose_name': 'Dispositivo FCM', 'verbose_name_plural': 'Dispositivos FCM'},
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
