# Generated by Django 6.0.1 on 2026-01-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primer_ingreso',
            field=models.BooleanField(default=True),
        ),
    ]
