# Generated by Django 6.0.1 on 2026-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_primer_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primer_ingreso',
            field=models.BooleanField(default=False),
        ),
    ]
