# Generated by Django 6.0.1 on 2026-03-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_primer_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_ingresos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
