# Generated by Django 6.0.1 on 2026-03-22 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ComunicadoVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_en', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistos', to='comunicados.comunicado')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_vistos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comunicado', 'tutor')},
            },
        ),
    ]
