# Generated by Django 6.0.1 on 2026-05-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comunicadoestudiante',
            new_name='comunicados_comunic_1ca04e_idx',
            old_name='comunicados_comunic_comuni_estado_idx',
        ),
    ]
