# Generated by Django 6.0.1 on 2026-03-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_profesorplan_profesor_curso'),
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='alcance',
            field=models.CharField(choices=[('TODOS', 'Todos los tutores'), ('GRADO', 'Un grado completo'), ('CURSO', 'Un curso específico')], default='TODOS', max_length=10),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to='academics.curso'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='grado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
