# Generated by Django 6.0.1 on 2026-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0002_comunicado_alcance_comunicado_curso_comunicado_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='alcance',
            field=models.CharField(choices=[('TODOS', 'Todos los tutores'), ('GRADO', 'Un grado completo'), ('CURSO', 'Un curso específico'), ('MIS_CURSOS', 'Todos mis cursos asignados')], default='TODOS', max_length=10),
        ),
    ]
