# Generated by Django 6.0.1 on 2026-04-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_profesorplan_eliminado'),
        ('comunicados', '0003_comunicado_alcance_mis_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='cursos_grupo',
            field=models.ManyToManyField(blank=True, related_name='comunicados_grupo', to='academics.curso'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='alcance',
            field=models.CharField(choices=[('TODOS', 'Todos los tutores'), ('GRADO', 'Un grado completo'), ('CURSO', 'Un curso específico'), ('MIS_CURSOS', 'Todos mis cursos asignados'), ('GRUPO', 'Grupo de cursos')], default='TODOS', max_length=10),
        ),
    ]
