# Generated by Django 6.0.1 on 2026-04-19 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_profesorplan_eliminado'),
        ('comunicados', '0004_alcance_grupo_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=10),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicados', to='academics.materia'),
        ),
    ]
