# Generated by Django 6.0.1 on 2026-01-20 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite_asistencia', models.DateField()),
                ('fecha_asistencia', models.DateField(blank=True, null=True)),
                ('asistencia', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No asistió'), ('ATRASO', 'atraso'), ('Informativo', 'Informativo')], db_index=True, default='PENDIENTE', max_length=30)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.estudiante')),
            ],
            options={
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['fecha_limite_asistencia'], name='discipline__fecha_l_733af7_idx')],
            },
        ),
    ]
