# Generated by Django 6.0.1 on 2026-02-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_citacion_actualizado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='asistencia',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VISTO', 'Visto'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No asistió'), ('ATRASO', 'Atraso'), ('Informativo', 'Informativo')], db_index=True, default='PENDIENTE', max_length=30),
        ),
    ]
