# Generated by Django 6.0.1 on 2026-03-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_alter_citacion_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='asistencia',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No asistió'), ('ATRASO', 'Atraso')], db_index=True, default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='estado',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('VISTO', 'Visto')], default='ENVIADA', max_length=20),
        ),
    ]
