# Generated by Django 6.0.1 on 2026-04-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0004_remove_visto_informativo_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='motivo',
            field=models.CharField(choices=[('FALTAS', 'Faltas'), ('ATRASOS', 'Atrasos'), ('CONDUCTA', 'Conducta'), ('RENDIMIENTO', 'Rendimiento'), ('DOCUMENTOS', 'Documentos'), ('REUNION', 'Reunión'), ('OTROS', 'Otros')], max_length=20),
        ),
    ]
