# Generated by Django 6.0.1 on 2026-04-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0005_motivo_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='motivo',
            field=models.CharField(choices=[('FALTAS', 'Faltas'), ('COMPORTAMIENTO', 'Comportamiento'), ('BAJO_RENDIMIENTO', 'Bajo rendimiento'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
