# Generated by Django 6.0.1 on 2026-04-19 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_profesorplan_eliminado'),
        ('discipline', '0006_motivos_actualizados'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citaciones', to='academics.materia'),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='asistencia',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No asistió'), ('ATRASO', 'Atraso'), ('ANULADA', 'Anulada')], db_index=True, default='PENDIENTE', max_length=30),
        ),
    ]
