# Generated by Django 6.0.1 on 2026-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0007_citacion_materia_y_anulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='motivo',
            field=models.CharField(choices=[('FALTAS', 'Faltas'), ('CONDUCTA', 'Conducta'), ('RENDIMIENTO', 'Rendimiento'), ('DOCUMENTOS', 'Documentos'), ('REUNION', 'Reunión'), ('COMPORTAMIENTO', 'Comportamiento'), ('BAJO_RENDIMIENTO', 'Bajo rendimiento'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
