# Generated by Django 6.0.1 on 2026-01-20 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.curso')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
