# Generated by Django 6.0.1 on 2026-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carnet',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Número de carnet'),
        ),
    ]
