# Generated by Django 6.0.1 on 2026-03-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_estudiante_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo en la unidad educativa'),
        ),
    ]
