# Generated by Django 6.0.1 on 2026-03-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_carnet_to_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='identificador',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Identificador'),
        ),
    ]
