# Generated by Django 6.0.1 on 2026-03-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_estudiante_identificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
